# -*- coding: utf-8 -*-
"""lab5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ib2d_saO1s5frY2tzG3OyrNwKA09FjQC
"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input
import matplotlib.pyplot as plt
import numpy as np

# Load Data
(x_train, _), (x_test, _) = tf.keras.datasets.mnist.load_data()

# Normalize
x_train = x_train.astype("float32") / 255.0
x_test = x_test.astype("float32") / 255.0

# Flatten
x_train = x_train.reshape(-1, 784)
x_test = x_test.reshape(-1, 784)

# Model
input_dim = 784
latent_dim = 32

# Encoder
encoder = Sequential([
    Input(shape=(input_dim,)),
    Dense(128, activation='relu'),
    Dense(latent_dim, activation='relu')
])

# Decoder
decoder = Sequential([
    Input(shape=(latent_dim,)),
    Dense(128, activation='relu'),
    Dense(input_dim, activation='sigmoid')
])

# Autoencoder
autoencoder = Sequential([encoder, decoder])

# Compile
autoencoder.compile(optimizer='adam', loss='mse')

# Train
history = autoencoder.fit(
    x_train, x_train,
    epochs=10,
    batch_size=128,
    validation_data=(x_test, x_test)
)

# Reconstruction
reconstructed = autoencoder.predict(x_test)

# Show Original vs Reconstructed
plt.figure(figsize=(6,3))

plt.subplot(1,2,1)
plt.imshow(x_test[0].reshape(28,28), cmap='gray')
plt.title("Original")

plt.subplot(1,2,2)
plt.imshow(reconstructed[0].reshape(28,28), cmap='gray')
plt.title("Reconstructed")

plt.show()

# 🔥 Loss Plot (IMPORTANT ADDITION)
plt.figure()
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.legend()
plt.title("Loss Curve")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.show()

import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Input, Layer
import numpy as np
import matplotlib.pyplot as plt

# Load Data
(x_train, _), (x_test, _) = tf.keras.datasets.mnist.load_data()

x_train = x_train.astype("float32") / 255.0
x_test = x_test.astype("float32") / 255.0

x_train = x_train.reshape(-1, 784)
x_test = x_test.reshape(-1, 784)

input_dim = 784
latent_dim = 2

# Sampling Layer (Reparameterization Trick)
class Sampling(Layer):
    def call(self, inputs):
        z_mean, z_log_var = inputs
        epsilon = tf.random.normal(shape=tf.shape(z_mean))
        return z_mean + tf.exp(0.5 * z_log_var) * epsilon

# Encoder
inputs = Input(shape=(input_dim,))
x = Dense(128, activation="relu")(inputs)
z_mean = Dense(latent_dim)(x)
z_log_var = Dense(latent_dim)(x)
z = Sampling()([z_mean, z_log_var])

encoder = Model(inputs, [z_mean, z_log_var, z])

# Decoder
latent_inputs = Input(shape=(latent_dim,))
x = Dense(128, activation="relu")(latent_inputs)
outputs = Dense(input_dim, activation="sigmoid")(x)

decoder = Model(latent_inputs, outputs)

# VAE Model
class VAE(Model):
    def __init__(self, encoder, decoder):
        super().__init__()
        self.encoder = encoder
        self.decoder = decoder

    def train_step(self, data):
        if isinstance(data, tuple):
            data = data[0]

        with tf.GradientTape() as tape:
            z_mean, z_log_var, z = self.encoder(data)
            reconstruction = self.decoder(z)

            # Reconstruction Loss
            recon_loss = tf.reduce_mean(
                tf.keras.losses.binary_crossentropy(data, reconstruction)
            ) * input_dim

            # KL Divergence
            kl_loss = -0.5 * tf.reduce_mean(
                1 + z_log_var - tf.square(z_mean) - tf.exp(z_log_var)
            )

            total_loss = recon_loss + kl_loss

        grads = tape.gradient(total_loss, self.trainable_weights)
        self.optimizer.apply_gradients(zip(grads, self.trainable_weights))

        return {
            "loss": total_loss,
            "reconstruction_loss": recon_loss,
            "kl_loss": kl_loss
        }

# Train
vae = VAE(encoder, decoder)
vae.compile(optimizer='adam')

history = vae.fit(x_train, epochs=10, batch_size=128)

# Reconstruction
z_mean, z_log_var, z = encoder.predict(x_test[:5])
reconstructed = decoder.predict(z)

# Show Results
plt.figure(figsize=(10,4))
for i in range(5):
    # Original
    plt.subplot(2,5,i+1)
    plt.imshow(x_test[i].reshape(28,28), cmap='gray')
    plt.title("Original")
    plt.axis("off")

    # Reconstructed
    plt.subplot(2,5,i+6)
    plt.imshow(reconstructed[i].reshape(28,28), cmap='gray')
    plt.title("VAE")
    plt.axis("off")

plt.show()

# 🔥 Loss Plot (important)
plt.plot(history.history['loss'], label='Total Loss')
plt.legend()
plt.title("VAE Loss")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.show()
#assignment
import tensorflow as tf
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Dense, Input, Layer
import numpy as np
import matplotlib.pyplot as plt

# =========================
# LOAD DATA
# =========================
(x_train, _), (x_test, _) = tf.keras.datasets.mnist.load_data()

x_train = x_train.astype("float32") / 255.0
x_test = x_test.astype("float32") / 255.0

x_train = x_train.reshape(-1, 784)
x_test = x_test.reshape(-1, 784)

input_dim = 784
latent_dim = 32

# =========================
# 1. AUTOENCODER
# =========================
encoder = Sequential([
    Input(shape=(input_dim,)),
    Dense(128, activation='relu'),
    Dense(latent_dim, activation='relu')
])

decoder = Sequential([
    Input(shape=(latent_dim,)),
    Dense(128, activation='relu'),
    Dense(input_dim, activation='sigmoid')
])

autoencoder = Sequential([encoder, decoder])
autoencoder.compile(optimizer='adam', loss='mse')

autoencoder.fit(x_train, x_train,
                epochs=5,
                batch_size=128,
                validation_data=(x_test, x_test))

# AE Prediction
ae_output = autoencoder.predict(x_test)


# =========================
# 2. VARIATIONAL AUTOENCODER
# =========================
latent_dim_vae = 2

class Sampling(Layer):
    def call(self, inputs):
        z_mean, z_log_var = inputs
        epsilon = tf.random.normal(shape=tf.shape(z_mean))
        return z_mean + tf.exp(0.5 * z_log_var) * epsilon

# Encoder
inputs = Input(shape=(input_dim,))
x = Dense(128, activation="relu")(inputs)
z_mean = Dense(latent_dim_vae)(x)
z_log_var = Dense(latent_dim_vae)(x)
z = Sampling()([z_mean, z_log_var])

encoder_vae = Model(inputs, [z_mean, z_log_var, z])

# Decoder
latent_inputs = Input(shape=(latent_dim_vae,))
x = Dense(128, activation="relu")(latent_inputs)
outputs = Dense(input_dim, activation="sigmoid")(x)

decoder_vae = Model(latent_inputs, outputs)

# VAE Model
class VAE(Model):
    def __init__(self, encoder, decoder):
        super().__init__()
        self.encoder = encoder
        self.decoder = decoder

    def train_step(self, data):
        if isinstance(data, tuple):
            data = data[0]

        with tf.GradientTape() as tape:
            z_mean, z_log_var, z = self.encoder(data)
            reconstruction = self.decoder(z)

            recon_loss = tf.reduce_mean(
                tf.keras.losses.binary_crossentropy(data, reconstruction)
            ) * input_dim

            kl_loss = -0.5 * tf.reduce_mean(
                1 + z_log_var - tf.square(z_mean) - tf.exp(z_log_var)
            )

            total_loss = recon_loss + kl_loss

        grads = tape.gradient(total_loss, self.trainable_weights)
        self.optimizer.apply_gradients(zip(grads, self.trainable_weights))

        return {"loss": total_loss}

vae = VAE(encoder_vae, decoder_vae)
vae.compile(optimizer='adam')

vae.fit(x_train, epochs=5, batch_size=128)

# VAE Prediction
z_mean, z_log_var, z = encoder_vae.predict(x_test[:len(x_test)])
vae_output = decoder_vae.predict(z)


# =========================
# 3. DENOISING AUTOENCODER
# =========================
noise_factor = 0.5

x_train_noisy = x_train + noise_factor * np.random.normal(size=x_train.shape)
x_test_noisy = x_test + noise_factor * np.random.normal(size=x_test.shape)

x_train_noisy = np.clip(x_train_noisy, 0., 1.)
x_test_noisy = np.clip(x_test_noisy, 0., 1.)

# New model (IMPORTANT: don't reuse trained encoder directly)
encoder_d = Sequential([
    Input(shape=(input_dim,)),
    Dense(128, activation='relu'),
    Dense(latent_dim, activation='relu')
])

decoder_d = Sequential([
    Input(shape=(latent_dim,)),
    Dense(128, activation='relu'),
    Dense(input_dim, activation='sigmoid')
])

denoise_ae = Sequential([encoder_d, decoder_d])
denoise_ae.compile(optimizer='adam', loss='mse')

denoise_ae.fit(x_train_noisy, x_train,
               epochs=5,
               batch_size=128,
               validation_data=(x_test_noisy, x_test))

# Denoising Prediction
denoise_output = denoise_ae.predict(x_test_noisy)


# =========================
# 4. COMPARISON
# =========================
plt.figure(figsize=(10,6))

for i in range(5):
    # Clean
    plt.subplot(4,5,i+1)
    plt.imshow(x_test[i].reshape(28,28), cmap='gray')
    plt.title("Clean")
    plt.axis("off")

    # AE
    plt.subplot(4,5,i+6)
    plt.imshow(ae_output[i].reshape(28,28), cmap='gray')
    plt.title("AE")
    plt.axis("off")

    # VAE
    plt.subplot(4,5,i+11)
    plt.imshow(vae_output[i].reshape(28,28), cmap='gray')
    plt.title("VAE")
    plt.axis("off")

    # Denoising AE
    plt.subplot(4,5,i+16)
    plt.imshow(denoise_output[i].reshape(28,28), cmap='gray')
    plt.title("Denoise")
    plt.axis("off")

plt.tight_layout()
plt.show()

