# -*- coding: utf-8 -*-
"""HMM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13_KjwymGlqq_J4sqAQfbkoJwTpmGYiax
"""

#IMPORT
import nltk
import numpy as np
from collections import defaultdict
from nltk.corpus import brown
nltk.download('brown') #this not required if run locally
nltk.download('universal_tagset')  #this not required if run locally

#Load tagged sentences
sentences = brown.tagged_sents(tagset='universal')

print(sentences[:5])

#Build counts
transition_counts = defaultdict(lambda: defaultdict(int))
emission_counts = defaultdict(lambda: defaultdict(int))
tag_counts = defaultdict(int)

# sentences format: [[(word, tag), (word, tag)], ...]
for sent in sentences:
    prev_tag = "<START>"

    for word, tag in sent:
        transition_counts[prev_tag][tag] += 1
        emission_counts[tag][word.lower()] += 1
        tag_counts[tag] += 1
        prev_tag = tag

    transition_counts[prev_tag]["<END>"] += 1


# Convert counts to probabilities
transition_probs = defaultdict(dict)
emission_probs = defaultdict(dict)

for prev_tag in transition_counts:
    total = sum(transition_counts[prev_tag].values())
    for tag in transition_counts[prev_tag]:
        transition_probs[prev_tag][tag] = transition_counts[prev_tag][tag] / total


for tag in emission_counts:
    total = tag_counts[tag]
    for word in emission_counts[tag]:
        emission_probs[tag][word] = emission_counts[tag][word] / total

# Viterbi Algorithm
def viterbi(sentence, tags, transition_probs, emission_probs):
    V = [{}]
    path = {}

    for tag in tags:
        V[0][tag] = (
            transition_probs["<START>"].get(tag, 1e-6) *
            emission_probs[tag].get(sentence[0], 1e-6)
        )
        path[tag] = [tag]

    for t in range(1, len(sentence)):
        V.append({})
        new_path = {}

        for curr_tag in tags:
            (prob, state) = max(
                (
                    V[t-1][prev_tag] *
                    transition_probs[prev_tag].get(curr_tag, 1e-6) *
                    emission_probs[curr_tag].get(sentence[t], 1e-6),
                    prev_tag
                )
                for prev_tag in tags
            )

            V[t][curr_tag] = prob
            new_path[curr_tag] = path[state] + [curr_tag]

        path = new_path

    (prob, state) = max((V[len(sentence)-1][tag], tag) for tag in tags)
    return path[state]


# Testing
tags = list(tag_counts.keys())
sentence = "mango monkey he is a ".split()

print(viterbi(sentence, tags, transition_probs, emission_probs))

# ===============================
# PLOTTING TRANSITION MATRIX
# ===============================
import seaborn as sns
import matplotlib.pyplot as plt

tags = list(tag_counts.keys())
matrix = []

for prev_tag in tags:
    row = []
    for curr_tag in tags:
        row.append(transition_probs.get(prev_tag, {}).get(curr_tag, 0))
    matrix.append(row)

matrix = np.array(matrix)

plt.figure(figsize=(8,6))
sns.heatmap(matrix, xticklabels=tags, yticklabels=tags, cmap="Blues")

plt.title("HMM Transition Probability Matrix")
plt.xlabel("Next Tag")
plt.ylabel("Previous Tag")

plt.show()


# ===============================
# PLOTTING EMISSION PROBABILITY
# ===============================

word = sentence[0]

values = []
for tag in tags:
    values.append(emission_probs[tag].get(word, 0))

plt.figure(figsize=(8,5))

plt.bar(tags, values)

plt.title(f"Emission Probabilities for '{word}'")
plt.xlabel("POS Tag")
plt.ylabel("Probability")

plt.show()



from gensim.models import Word2Vec
from nltk.corpus import brown
import nltk
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

# nltk.download('brown')


# ==========================
# PREPARE SENTENCES
# ==========================
sentences = [[word.lower() for word in sent] for sent in brown.sents()]


# ==========================
# TRAIN WORD2VEC (CBOW)
# ==========================
model = Word2Vec(
    sentences,
    vector_size=100,
    window=5,
    min_count=2,
    workers=4,
    epochs=20
)

print("CBOW model trained")


# ==========================
# TRAIN WORD2VEC (SKIP-GRAM)
# ==========================
skipgram_model = Word2Vec(
    sentences,
    vector_size=100,
    window=5,
    min_count=2,
    workers=4,
    sg=1,          # Skip-gram
    epochs=20
)

print("Skip-gram model trained")


# ==========================
# SIMILAR WORDS
# ==========================
print("\nSimilar words to 'king':")
print(model.wv.most_similar("king"))


# ==========================
# WORD ANALOGY
# ==========================
print("\nAnalogy: king - man + woman")
print(model.wv.most_similar(
    positive=["king", "woman"],
    negative=["man"]
))


# ==========================
# VISUALIZE WORD EMBEDDINGS
# ==========================

words = list(model.wv.index_to_key[:100])
vectors = [model.wv[word] for word in words]

pca = PCA(n_components=2)
result = pca.fit_transform(vectors)

plt.figure(figsize=(10,7))

for i, word in enumerate(words):
    x, y = result[i]
    plt.scatter(x, y)
    plt.text(x+0.01, y+0.01, word)

plt.title("Word2Vec Embedding (PCA Projection)")
plt.show()

"""**assignment**"""

#import
import nltk
from nltk.corpus import brown
from collections import defaultdict
import random

# nltk.download('brown')
# nltk.download('universal_tagset')

sentences = brown.tagged_sents(tagset='universal')

# Split train / test
train_sentences = sentences[:-100]
print(len(train_sentences))
test_sentences = sentences[-100:]
print(len(test_sentences))

transition_counts = defaultdict(lambda: defaultdict(int))
emission_counts = defaultdict(lambda: defaultdict(int))
tag_counts = defaultdict(int)

vocab = set()

# =========================
# TRAINING
# =========================
for sent in train_sentences:
    prev_tag = "<START>"

    for word, tag in sent:
        word = word.lower()
        vocab.add(word)

        transition_counts[prev_tag][tag] += 1
        emission_counts[tag][word] += 1
        tag_counts[tag] += 1

        prev_tag = tag

    transition_counts[prev_tag]["<END>"] += 1



# LAPLACE SMOOTHING

transition_probs = defaultdict(dict)
emission_probs = defaultdict(dict)

tags = list(tag_counts.keys())

for prev_tag in transition_counts:
    total = sum(transition_counts[prev_tag].values()) + len(tags)

    for tag in tags:
        count = transition_counts[prev_tag][tag]
        transition_probs[prev_tag][tag] = (count + 1) / total


for tag in emission_counts:
    total = tag_counts[tag] + len(vocab)

    for word in vocab:
        count = emission_counts[tag][word]
        emission_probs[tag][word] = (count + 1) / total


# =========================
# VITERBI WITH UNKNOWN WORD
# =========================
def viterbi(sentence):

    V = [{}]
    path = {}

    for tag in tags:
        #unkown are handled
        emission = emission_probs[tag].get(sentence[0], 1/len(vocab))

        V[0][tag] = transition_probs["<START>"].get(tag,1e-6) * emission
        path[tag] = [tag]

    for t in range(1,len(sentence)):
        V.append({})
        new_path = {}

        for curr_tag in tags:

            emission = emission_probs[curr_tag].get(sentence[t],1/len(vocab))

            prob,state = max(
                (V[t-1][prev_tag] *
                 transition_probs[prev_tag].get(curr_tag,1e-6) *
                 emission, prev_tag)
                for prev_tag in tags
            )

            V[t][curr_tag] = prob
            new_path[curr_tag] = path[state] + [curr_tag]

        path = new_path

    prob,state = max((V[len(sentence)-1][tag],tag) for tag in tags)

    return path[state]

#accuracy
correct = 0
total = 0

for sent in test_sentences:

    words = [w.lower() for w,t in sent]
    true_tags = [t for w,t in sent]

    pred_tags = viterbi(words)

    for p,t in zip(pred_tags,true_tags):
        if p == t:
            correct += 1
        total += 1

accuracy = correct / total

print("HMM Accuracy:",accuracy*100)

from gensim.models import Word2Vec
from nltk.corpus import brown

sentences = [[w.lower() for w in sent] for sent in brown.sents()]

# 50 dimensional
model50 = Word2Vec(
    sentences,
    vector_size=50,
    window=5,
    min_count=2,
    workers=4,
    epochs=20
)

# 200 dimensional
model200 = Word2Vec(
    sentences,
    vector_size=200,
    window=5,
    min_count=2,
    workers=4,
    epochs=20
)

print(model50.wv.most_similar("king"))
print(model200.wv.most_similar("king"))

import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

def plot_embeddings(model, title):

    words = list(model.wv.index_to_key[:100])
    vectors = [model.wv[word] for word in words]

    pca = PCA(n_components=2)
    result = pca.fit_transform(vectors)

    plt.figure(figsize=(10,7))

    for i, word in enumerate(words):
        x, y = result[i]
        plt.scatter(x, y)
        plt.text(x+0.01, y+0.01, word, fontsize=9)

    plt.title(title)
    plt.xlabel("PCA Component 1")
    plt.ylabel("PCA Component 2")
    plt.show()


# Plot for 50-dim model
plot_embeddings(model50, "Word2Vec Embedding (50 Dimensions)")

# Plot for 200-dim model
plot_embeddings(model200, "Word2Vec Embedding (200 Dimensions)")

from sklearn.cluster import KMeans
import numpy as np

words = list(model50.wv.index_to_key[:500])

vectors = np.array([model50.wv[w] for w in words])

kmeans = KMeans(n_clusters=10, random_state=0)
labels = kmeans.fit_predict(vectors)

for i in range(10):
    print("\nCluster",i)
    for j,word in enumerate(words):
        if labels[j] == i:
            print(word,end=" ")

#sentence similarity
import numpy as np

def sentence_vector(sentence, model):

    words = sentence.lower().split()

    vecs = []

    for w in words:
        if w in model.wv:
            vecs.append(model.wv[w])

    return np.mean(vecs, axis=0)


def cosine_similarity(v1,v2):

    return np.dot(v1,v2) / (np.linalg.norm(v1)*np.linalg.norm(v2))


s1 = "Boys play rugby"
s2 = "Girl play volleyball"

v1 = sentence_vector(s1, model200)
v2 = sentence_vector(s2, model200)

print("Sentence similarity:", cosine_similarity(v1,v2))

