# -*- coding: utf-8 -*-
"""Rnn_LSTM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pTSnGeIunOY7Q8NWWnvObDrLA0OhuNG0
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, SimpleRNN, Dense
from tensorflow.keras.callbacks import EarlyStopping

# Step 1: Load Dataset
train = pd.read_csv("mitbih_train.csv")
test = pd.read_csv("mitbih_test.csv", header=None)
print("Train shape",train.shape)
print("Test shape",test.shape)

# Features and labels
X_train = train.iloc[:, :-1].values
y_train = train.iloc[:, -1].values

X_test = test.iloc[:, :-1].values
y_test = test.iloc[:, -1].values
print("X_train shape",X_train.shape)
print("y_train shape",y_train.shape)
print("X_test shape",X_test.shape)
print("y_test shape",y_test.shape)
print("Unique",pd.Series(y_test).value_counts())

# Step 2: Normalize Data
scaler = MinMaxScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Step 3: Train Validation Split
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

#Step 4: Reshape for LSTM/RNN

X_train = X_train.reshape(-1, 187, 1)
X_val = X_val.reshape(-1, 187, 1)
X_test = X_test.reshape(-1, 187, 1)

# LSTM MODEL
lstm_model = Sequential([
    LSTM(64, input_shape=(187,1)),
    Dense(32, activation='relu'),
    Dense(5, activation='softmax')
])

lstm_model.summary()


#model compile
lstm_model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

print("\nTraining LSTM Model...\n")

lstm_history = lstm_model.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=15,
    batch_size=64,
    callbacks=[EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True)]
)

# Evaluate
lstm_loss, lstm_acc = lstm_model.evaluate(X_test, y_test)

print("LSTM Test Accuracy:", lstm_acc*100)
print("LSTM Test loss:",lstm_loss)

# Confusion Matrix and Classification Report
from sklearn.metrics import confusion_matrix, classification_report


y_pred_prob = lstm_model.predict(X_test)
y_pred = np.argmax(y_pred_prob, axis=1)
cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title('LSTM Confusion Matrix')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

print('\nLSTM Classification Report:')
print(classification_report(y_test, y_pred))

#Rnn Model
rnn_model = Sequential([
    SimpleRNN(64, input_shape=(187,1)),
    Dense(32, activation='relu'),
    Dense(5, activation='softmax')
])

rnn_model.summary()

#model compile
rnn_model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

print("\nTraining RNN Model...\n")

#Rnn Model Fit
rnn_history = rnn_model.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=15,
    batch_size=64,
    callbacks=[EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True)]
)

# Evaluate
rnn_loss, rnn_acc = rnn_model.evaluate(X_test, y_test)

print("RNN Test Accuracy:", rnn_acc*100)
print("RNN Testing Loss",rnn_loss)

#confusion_matrix
y_pred_prob = rnn_model.predict(X_test)
y_pred = np.argmax(y_pred_prob, axis=1)
cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='magma')
plt.title('RNN Confusion Matrix')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

print('\nRNN Classification Report:')
print(classification_report(y_test, y_pred))

#plot comparision
plt.figure(figsize=(10,5))
plt.subplot(2,1,1)
plt.plot(lstm_history.history['loss'], label='LSTM Training Loss')
plt.plot(lstm_history.history['val_loss'], label='LSTM Validation Loss')
plt.plot(rnn_history.history['loss'], label='RNN Training Loss')
plt.plot(rnn_history.history['val_loss'], label='RNN Validation Loss')
plt.title('LSTM  RNN Training and Validation Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()

plt.subplot(2,1,2)
plt.plot(lstm_history.history['accuracy'], label='LSTM Training Accuracy')
plt.plot(lstm_history.history['val_accuracy'], label='LSTM Validation Accuracy')
plt.plot(rnn_history.history['accuracy'], label='RNN Training Accuracy')
plt.plot(rnn_history.history['val_accuracy'], label='RNN Validation Accuracy')
plt.title('LSTM  RNN Training and Validation Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()



plt.tight_layout()
plt.show()



# #plot comparision
# plt.figure(figsize=(10,5))
# plt.subplot(2,2,1)
# plt.plot(lstm_history.history['loss'], label='LSTM Training Loss')
# plt.plot(lstm_history.history['val_loss'], label='LSTM Validation Loss')
# plt.title('LSTM Training and Validation Loss')
# plt.xlabel('Epochs')
# plt.ylabel('Loss')
# plt.legend()

# plt.subplot(2,2,2)
# plt.plot(lstm_history.history['accuracy'], label='LSTM Training Accuracy')
# plt.plot(lstm_history.history['val_accuracy'], label='LSTM Validation Accuracy')
# plt.title('LSTM Training and Validation Accuracy')
# plt.xlabel('Epochs')
# plt.ylabel('Accuracy')
# plt.legend()

# plt.subplot(2,2,3)
# plt.plot(rnn_history.history['loss'], label='RNN Training Loss')
# plt.plot(rnn_history.history['val_loss'], label='RNN Validation Loss')
# plt.title('RNN Training and Validation Loss')
# plt.xlabel('Epochs')
# plt.ylabel('Loss')
# plt.legend()

# plt.subplot(2,2,4)
# plt.plot(rnn_history.history['accuracy'], label='RNN Training Accuracy')
# plt.plot(rnn_history.history['val_accuracy'], label='RNN Validation Accuracy')
# plt.title('RNN Training and Validation Accuracy')
# plt.xlabel('Epochs')
# plt.ylabel('Accuracy')
# plt.legend()

# plt.tight_layout()
# plt.show()

train.iloc[:, -1].value_counts().sort_index()