# -*- coding: utf-8 -*-
"""GRU.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ac4ptnHmCaFyEN5S7eOqOChvk4OudkrJ
"""

import numpy as np

# Activation functions
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def tanh(x):
    return np.tanh(x)

# GRU Cell
def GRU_Cell(x_t, h_tminus_1, W_z, U_z, b_z,W_r, U_r, b_r,W_h, U_h, b_h):

    # Update gate
    z_t = sigmoid(np.dot(W_z, x_t) + np.dot(U_z, h_tminus_1) + b_z)

    # Reset gate
    r_t = sigmoid(np.dot(W_r, x_t) + np.dot(U_r, h_tminus_1) + b_r)

    # Candidate hidden state
    h_tilde = tanh(np.dot(W_h, x_t) + np.dot(U_h, r_t * h_tminus_1) + b_h)

    # Final hidden state
    h_t = (1 - z_t) * h_tminus_1 + z_t * h_tilde

    return h_t

# Dimensions
input_size = 4
hidden_size = 3

# Random input and hidden state
x_t = np.random.randn(input_size, 1)
h_prev = np.random.randn(hidden_size, 1)

# Initialize weights
W_z = np.random.randn(hidden_size, input_size)
U_z = np.random.randn(hidden_size, hidden_size)
b_z = np.random.randn(hidden_size, 1)

W_r = np.random.randn(hidden_size, input_size)
U_r = np.random.randn(hidden_size, hidden_size)
b_r = np.random.randn(hidden_size, 1)

W_h = np.random.randn(hidden_size, input_size)
U_h = np.random.randn(hidden_size, hidden_size)
b_h = np.random.randn(hidden_size, 1)

print("Input Shape:", x_t.shape)
print("Hidden State Shape:", h_prev.shape)

print("Update Gate")
print("W_z Shape:", W_z.shape,"\n weight:",W_z)
print("U_z Shape:", U_z.shape,"\n weight:",U_z)
print("b_z Shape:", b_z.shape,"\n weight:",b_z)

print("Reset Gate")
print("W_r Shape:", W_r.shape,"\n weight:",W_r)
print("U_r Shape:", U_r.shape,"\n weight:",U_r)
print("b_r Shape:", b_r.shape,"\n weight:",b_r)

print("Hidden Gate")
print("W_h shape:",W_h.shape,"\n weight:",W_h)
print("U_h shape:",U_h.shape,"\n weight:",U_h)
print("b_h shape:",b_h.shape,"\n weight:",b_h)

# Forward pass
h_t = GRU_Cell(x_t, h_prev,
               W_z, U_z, b_z,
               W_r, U_r, b_r,
               W_h, U_h, b_h)

print("New Hidden State:\n", h_t)

"""#Assignment 2"""

import numpy as np
import pandas as pd
import re
import nltk
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, GRU, Dense, Input

# Download dataset from Kaggle and place imdb.csv
df = pd.read_csv("/content/IMDB Dataset.csv")

# Convert labels to binary
# df['sentiment'] = df['sentiment'].map({'positive': 1, 'negative': 0})
df['sentiment'] = df['sentiment'].astype('category').cat.codes

#Data Preprocessing
nltk.download('stopwords')
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = text.lower()
    text = re.sub(r'<.*?>', '', text)  # remove HTML
    text = re.sub(r'[^a-zA-Z]', ' ', text)
    words = text.split()
    words = [w for w in words if w not in stop_words]
    return " ".join(words)

df['review'] = df['review'].apply(clean_text)

#Tokenization + Padding
vocab_size = 10000
max_len = 200

tokenizer = Tokenizer(num_words=vocab_size)
tokenizer.fit_on_texts(df['review'])

X = tokenizer.texts_to_sequences(df['review'])
X = pad_sequences(X, maxlen=max_len)

y = df['sentiment'].values

#train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# model architecture

model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=128,input_shape=(max_len,)),
    GRU(128, return_sequences=False),
    Dense(1, activation='sigmoid')
])

model.summary()

#compile the model
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

history = model.fit(X_train, y_train,epochs=5,batch_size=64,validation_split=0.2)

y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5).astype(int)

from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

