# -*- coding: utf-8 -*-
"""lab9s2s.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CC8BHKCq_4ZYX0Da-nneHtxFr8YmlVdx
"""

import tensorflow as tf
import matplotlib.pyplot as plt

# Toy Dataset
input_texts = ['i am happy', 'i love you', 'he is good']
target_texts = ['je suis heureux', 'je t aime', 'il est bon']

# Tokenization
tokenizer = tf.keras.preprocessing.text.Tokenizer(filters='')
tokenizer.fit_on_texts(input_texts + target_texts)

input_seq = tokenizer.texts_to_sequences(input_texts)
target_seq = tokenizer.texts_to_sequences(target_texts)

input_seq = tf.keras.preprocessing.sequence.pad_sequences(input_seq, padding='post')
target_seq = tf.keras.preprocessing.sequence.pad_sequences(target_seq, padding='post')

vocab_size = len(tokenizer.word_index) + 1

# Encoder
def build_encoder(vocab_size, embedding_dim, enc_units):
    encoder = tf.keras.Sequential([
        tf.keras.layers.Embedding(vocab_size, embedding_dim),
        tf.keras.layers.GRU(enc_units, return_sequences=True, return_state=True)
    ])
    return encoder

class BahdanauAttention(tf.keras.layers.Layer):
    def __init__(self, units):
        super().__init__()
        self.W1 = tf.keras.layers.Dense(units)
        self.W2 = tf.keras.layers.Dense(units)
        self.V = tf.keras.layers.Dense(1)

    def call(self, query, values):
        query = tf.expand_dims(query, 1)

        score = self.V(tf.nn.tanh(
            self.W1(values) + self.W2(query)
        ))

        attention_weights = tf.nn.softmax(score, axis=1)

        context_vector = attention_weights * values
        context_vector = tf.reduce_sum(context_vector, axis=1)

        return context_vector, attention_weights

# Decoder
class Decoder(tf.keras.Model):
    def __init__(self, vocab_size, embedding_dim, units):
        super().__init__()
        self.embedding = tf.keras.layers.Embedding(vocab_size, embedding_dim)
        self.gru = tf.keras.layers.GRU(units, return_sequences=True, return_state=True)
        self.fc = tf.keras.layers.Dense(vocab_size)
        self.attention = BahdanauAttention(units)

    def call(self, x, hidden, enc_output):
        context_vector, attention_weights = self.attention(hidden, enc_output)

        x = self.embedding(x)
        x = tf.concat([tf.expand_dims(context_vector, 1), x], axis=-1)

        output, state = self.gru(x)
        output = self.fc(output)

        return output, state, attention_weights

# Forward Pass
embedding_dim = 64
units = 128

encoder = build_encoder(vocab_size, embedding_dim, units)
decoder = Decoder(vocab_size, embedding_dim, units)

sample_input = tf.convert_to_tensor(input_seq)
enc_output, enc_hidden = encoder(sample_input)

batch_size = input_seq.shape[0]aq23e

dec_input = tf.expand_dims([tokenizer.word_index['je']] * batch_size, 1)

output, state, attn = decoder(dec_input, enc_hidden, enc_output)

print("Attention shape:", attn.shape)

# -----------------------------
# Visualization
# -----------------------------
plt.imshow(attn[0].numpy(), cmap='viridis')
plt.colorbar()
plt.title('Attention Weights')
plt.show()

"""**Assignment 2**"""

import tensorflow as tf

# Given values and query
values = tf.constant([[[1.0, 2.0, 0.0],
                       [0.0, 1.0, 3.0],
                       [2.0, 0.0, 1.0]]])

query = tf.constant([[1.0, 1.0, 1.0]])

# Bahdanau Attention
class BahdanauAttention(tf.keras.layers.Layer):
    def __init__(self, units):
        super().__init__()
        self.W1 = tf.keras.layers.Dense(units)
        self.W2 = tf.keras.layers.Dense(units)
        self.V = tf.keras.layers.Dense(1)

    def call(self, query, values):
        query = tf.expand_dims(query, 1)

        score = self.V(tf.nn.tanh(
            self.W1(values) + self.W2(query)
        ))

        attention_weights = tf.nn.softmax(score, axis=1)

        context_vector = attention_weights * values
        context_vector = tf.reduce_sum(context_vector, axis=1)

        return score, attention_weights, context_vector

# Run Attention
# -----------------------------
attention = BahdanauAttention(units=8)

scores, weights, context = attention(query, values)

print("Attention Scores:\n", scores.numpy())
print("\nAttention Weights:\n", weights.numpy())
print("\nContext Vector:\n", context.numpy())

# Visualization
# -----------------------------
import matplotlib.pyplot as plt

# weights shape: (1, 3, 1) → convert to (3, 1)
attn = weights.numpy().squeeze()   # shape becomes (3,)

# reshape to 2D for imshow
attn = attn.reshape(-1, 1)

plt.imshow(attn, cmap='viridis')
plt.colorbar()
plt.title('Attention Weights')
plt.xlabel('Query')
plt.ylabel('Values Index')
plt.show()