# -*- coding: utf-8 -*-
"""lab_10_transformer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TEAK5H-6GIin-XlPo4MZEXX2lsBA0wbt
"""

#import library
import tensorflow as tf
from tensorflow.keras import layers
import numpy as np

# Dataset
texts = [
    "i love this movie", "this is amazing", "i like it", "so good",
    "i hate this", "this is bad", "terrible experience", "not good"
] * 20

labels = [1,1,1,1,0,0,0,0] * 20

# Tokenization
vocab_size = 1000
max_len = 10

vectorizer = layers.TextVectorization(
    max_tokens=vocab_size,
    output_mode="int",
    output_sequence_length=max_len
)

vectorizer.adapt(texts)

X = vectorizer(np.array(texts))
y = np.array(labels)

# Positional Embedding
class PositionalEmbedding(layers.Layer):
    def __init__(self, max_len, vocab_size, embed_dim):
        super().__init__()
        self.token_emb = layers.Embedding(vocab_size, embed_dim)
        self.pos_emb = layers.Embedding(input_dim=max_len, output_dim=embed_dim)

    def call(self, x):
        positions = tf.range(start=0, limit=tf.shape(x)[-1], delta=1)
        return self.token_emb(x) + self.pos_emb(positions)

# Transformer Block
class TransformerBlock(layers.Layer):
    def __init__(self, embed_dim, num_heads, ff_dim):
        super().__init__()
        self.att = layers.MultiHeadAttention(
            num_heads=num_heads,
            key_dim=embed_dim
        )
        self.ffn = tf.keras.Sequential([
            layers.Dense(ff_dim, activation="relu"),
            layers.Dense(embed_dim),
        ])
        self.norm1 = layers.LayerNormalization()
        self.norm2 = layers.LayerNormalization()

    def call(self, inputs):
        attn_output = self.att(inputs, inputs)
        out1 = self.norm1(inputs + attn_output)
        ffn_output = self.ffn(out1)
        return self.norm2(out1 + ffn_output)

# Build Model
# -----------------------------
embed_dim = 32
num_heads = 2
ff_dim = 32

inputs = layers.Input(shape=(max_len,))
x = PositionalEmbedding(max_len, vocab_size, embed_dim)(inputs)
x = TransformerBlock(embed_dim, num_heads, ff_dim)(x)
x = layers.GlobalAveragePooling1D()(x)
x = layers.Dense(20, activation="relu")(x)
outputs = layers.Dense(1, activation="sigmoid")(x)

model = tf.keras.Model(inputs, outputs)

model.summary()

# Compile & Train
model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

history = model.fit(
    X, y,
    epochs=10,
    batch_size=8,
    validation_split=0.2
)

loss,accuracy=model.evaluate(X,y)
print("loss:",loss)
print("accuracy:",accuracy)

#plot accuracy and loss
import matplotlib.pyplot as plt
plt.figure(figsize=(12,12))
plt.subplot(2,1,1)
plt.plot(history.history['accuracy'],label='Training Accuracy')
plt.plot(history.history['val_accuracy'],label='Validation Accuracy')
plt.title('Accuracy Plot')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend()
plt.subplot(2,1,2)
plt.plot(history.history['loss'],label='Training Loss')
plt.plot(history.history['val_loss'],label='Validation Loss')
plt.title('Loss Plot')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend()
plt.show()

"""**Assignment**"""

import numpy as np

# Input: "I love AI"
# n = 3, d_model = 4
X = np.array([
    [1, 0, 1, 0],   # I
    [0, 1, 0, 1],   # love
    [1, 1, 0, 0]    # AI
])

n, d_model = 3,4
h = 2
d_k = d_model // h

# Random Weight Matrices
np.random.seed(0)

Wq1 = np.random.rand(d_model, d_k)
Wk1 = np.random.rand(d_model, d_k)
Wv1 = np.random.rand(d_model, d_k)
Wq2 = np.random.rand(d_model, d_k)
Wk2 = np.random.rand(d_model, d_k)
Wv2 = np.random.rand(d_model, d_k)
Wo =  np.random.rand(d_model, d_model)

# Step 1: Compute Q, K, V for head 1
Q1 = X @ Wq1
K1 = X @ Wk1
V1 = X @ Wv1
print("head 1")
print("Q:\n", Q1)
print("\nK:\n", K1)
print("\nV:\n", V1)

#head2
Q2 = X @ Wq2
K2 = X @ Wk2
V2 = X @ Wv2
print("head 2")
print("Q:\n", Q2)
print("\nK:\n", K2)
print("\nV:\n", V2)

# Step 2: Scaled Dot-Product Attention
def attention(Q, K, V):
    scores = Q @ K.T / np.sqrt(d_k)
    softmax = np.exp(scores) / np.sum(np.exp(scores), axis=-1, keepdims=True)
    output = softmax @ V
    return output, softmax

head_outputs = []

out1, soft1 = attention(Q1, K1, V1)
print("Head 1 Softmax:\n", soft1)
print("Head 1 Output:\n", out1)


out2, soft2 = attention(Q2, K2, V2)
print("\nHead 2 Softmax:\n", soft2)
print("Head 2 Output:\n", out2)

# Step 4: Concatenate Heads
concat = np.concatenate([out1,out2], axis=-1)

# Step 5: Final Linear Projection
final_output = concat @ Wo

# Print Results
# print("Q:\n", Q)
print("\nConcatenation Attention Output:\n", concat)
print("\nFinal Output:\n", final_output)

