# -*- coding: utf-8 -*-
"""lab-11_gan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qywy6704uAMtV_fhIT5H1cokP-vx20xy
"""

import tensorflow as tf
from tensorflow.keras import layers
import numpy as np
import matplotlib.pyplot as plt

# PARAMETERS
# -------------------------
IMG_SIZE = 64
BATCH_SIZE = 32
LATENT_DIM = 100
EPOCHS = 5

#dataset

DATA_DIR = "/content/img_align_celeba/img_align_celeba"  # change path


dataset = tf.keras.preprocessing.image_dataset_from_directory(
    DATA_DIR,
    label_mode=None,
    image_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE
)

def preprocess(images):
    return (images / 127.5) - 1

dataset = dataset.map(preprocess)

# GENERATOR
# -------------------------
def build_generator():
    model = tf.keras.Sequential([
        layers.Dense(8*8*256, input_dim=LATENT_DIM),
        layers.Reshape((8, 8, 256)),

        layers.Conv2DTranspose(128, 4, strides=2, padding='same'),
        layers.BatchNormalization(),
        layers.ReLU(),

        layers.Conv2DTranspose(64, 4, strides=2, padding='same'),
        layers.BatchNormalization(),
        layers.ReLU(),

        layers.Conv2DTranspose(3, 4, strides=2, padding='same', activation='tanh')
    ])
    return model

# -------------------------
# DISCRIMINATOR

def build_discriminator():
    model = tf.keras.Sequential([
        layers.Conv2D(64, 4, strides=2, padding='same'),
        layers.LeakyReLU(0.2),

        layers.Conv2D(128, 4, strides=2, padding='same'),
        layers.LeakyReLU(0.2),

        layers.Flatten(),
        layers.Dense(1, activation='sigmoid')
    ])
    return model

generator = build_generator()
discriminator = build_discriminator()

cross_entropy = tf.keras.losses.BinaryCrossentropy()

g_optimizer = tf.keras.optimizers.Adam(1e-4)
d_optimizer = tf.keras.optimizers.Adam(1e-4)

# TRAIN STEP
# -------------------------
@tf.function
def train_step(real_images):
    noise = tf.random.normal([BATCH_SIZE, LATENT_DIM])

    with tf.GradientTape() as gen_tape, tf.GradientTape() as disc_tape:
        fake_images = generator(noise)

        real_output = discriminator(real_images)
        fake_output = discriminator(fake_images)

        d_loss_real = cross_entropy(tf.ones_like(real_output), real_output)
        d_loss_fake = cross_entropy(tf.zeros_like(fake_output), fake_output)
        d_loss = d_loss_real + d_loss_fake

        g_loss = cross_entropy(tf.ones_like(fake_output), fake_output)

    grads_g = gen_tape.gradient(g_loss, generator.trainable_variables)
    grads_d = disc_tape.gradient(d_loss, discriminator.trainable_variables)

    g_optimizer.apply_gradients(zip(grads_g, generator.trainable_variables))
    d_optimizer.apply_gradients(zip(grads_d, discriminator.trainable_variables))

# GENERATE IMAGES
# -------------------------
def generate_images(epoch):
    noise = tf.random.normal([16, LATENT_DIM])
    images = generator(noise)

    images = (images + 1) / 2

    plt.figure(figsize=(4,4))
    for i in range(16):
        plt.subplot(4,4,i+1)
        plt.imshow(images[i])
        plt.axis('off')
    plt.savefig(f"epoch_{epoch}.png")
    plt.close()

# -------------------------
# TRAIN LOOP
# -------------------------
for epoch in range(EPOCHS):
    for image_batch in dataset:
        train_step(image_batch)

    generate_images(epoch)
    print(f"Epoch {epoch+1} completed")

print("Training Finished!")

