# -*- coding: utf-8 -*-
"""lab-11-gan-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bT_Z42l-s8Ei7BEu50_nHMONVfGizbLK
"""

!kaggle datasets download -d paultimothymooney/chest-xray-pneumonia

!unzip /content/chest-xray-pneumonia.zip

import os
import cv2
import numpy as np
from tqdm import tqdm
path="/content/chest_xray"
IMG_SIZE = 256

def preprocess_image(img_path):
    img = cv2.imread(img_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
    img = img / 255.0
    img = np.expand_dims(img, axis=-1)
    return img

def degrade_image(img):
    # Gaussian blur
    blur = cv2.GaussianBlur(img, (5,5), 0)

    # Downsample + Upsample
    small = cv2.resize(blur, (64,64))
    degraded = cv2.resize(small, (IMG_SIZE, IMG_SIZE))

    return degraded

def load_dataset(folder):
    low_quality = []
    high_quality = []

    for root, dirs, files in os.walk(folder):
        for file in tqdm(files):
            if file.endswith(".jpeg") or file.endswith(".jpg"):
                path = os.path.join(root, file)
                img = preprocess_image(path)
                degraded = degrade_image(img)

                high_quality.append(img)
                low_quality.append(degraded)

    return np.array(low_quality), np.array(high_quality)

data_dir = path + "/chest_xray/train"
low_imgs, high_imgs = load_dataset(data_dir)

print(low_imgs.shape, high_imgs.shape)



import tensorflow as tf
from tensorflow.keras import layers

def downsample(filters, size=4, apply_batchnorm=True):
    result = tf.keras.Sequential()
    result.add(layers.Conv2D(filters, size, strides=2, padding='same'))

    if apply_batchnorm:
        result.add(layers.BatchNormalization())

    result.add(layers.LeakyReLU())
    return result

def upsample(filters, size=4, apply_dropout=False):
    result = tf.keras.Sequential()
    result.add(layers.Conv2DTranspose(filters, size, strides=2, padding='same'))
    result.add(layers.BatchNormalization())

    if apply_dropout:
        result.add(layers.Dropout(0.5))

    result.add(layers.ReLU())
    return result

def build_generator():
    inputs = layers.Input(shape=[256,256,1])

    # Encoder
    d1 = downsample(64, apply_batchnorm=False)(inputs)
    d2 = downsample(128)(d1)
    d3 = downsample(256)(d2)

    # Bottleneck
    b = downsample(512)(d3)

    # Decoder
    u1 = upsample(256)(b)
    u1 = layers.Concatenate()([u1, d3])

    u2 = upsample(128)(u1)
    u2 = layers.Concatenate()([u2, d2])

    u3 = upsample(64)(u2)
    u3 = layers.Concatenate()([u3, d1])

    outputs = layers.Conv2DTranspose(1, 4, strides=2, padding='same', activation='tanh')(u3)

    return tf.keras.Model(inputs, outputs)

generator = build_generator()
generator.summary()

def build_discriminator():
    inp = layers.Input(shape=[256,256,1])
    tar = layers.Input(shape=[256,256,1])

    x = layers.Concatenate()([inp, tar])

    d1 = downsample(64, apply_batchnorm=False)(x)
    d2 = downsample(128)(d1)
    d3 = downsample(256)(d2)

    x = layers.Flatten()(d3)
    x = layers.Dense(512, activation='relu')(x)
    output = layers.Dense(1, activation='sigmoid')(x)

    return tf.keras.Model([inp, tar], output)

discriminator = build_discriminator()
discriminator.summary()

loss_obj = tf.keras.losses.BinaryCrossentropy()

def generator_loss(disc_generated_output, gen_output, target):
    adv_loss = loss_obj(tf.ones_like(disc_generated_output), disc_generated_output)
    l1_loss = tf.reduce_mean(tf.abs(target - gen_output))

    return adv_loss + (100 * l1_loss)

def discriminator_loss(disc_real_output, disc_generated_output):
    real_loss = loss_obj(tf.ones_like(disc_real_output), disc_real_output)
    fake_loss = loss_obj(tf.zeros_like(disc_generated_output), disc_generated_output)

    return real_loss + fake_loss

generator_optimizer = tf.keras.optimizers.Adam(2e-4, beta_1=0.5)
discriminator_optimizer = tf.keras.optimizers.Adam(2e-4, beta_1=0.5)

@tf.function
def train_step(input_image, target):
    with tf.GradientTape() as gen_tape, tf.GradientTape() as disc_tape:

        gen_output = generator(input_image, training=True)

        disc_real_output = discriminator([input_image, target], training=True)
        disc_fake_output = discriminator([input_image, gen_output], training=True)

        gen_loss = generator_loss(disc_fake_output, gen_output, target)
        disc_loss = discriminator_loss(disc_real_output, disc_fake_output)

    gen_gradients = gen_tape.gradient(gen_loss, generator.trainable_variables)
    disc_gradients = disc_tape.gradient(disc_loss, discriminator.trainable_variables)

    generator_optimizer.apply_gradients(zip(gen_gradients, generator.trainable_variables))
    discriminator_optimizer.apply_gradients(zip(disc_gradients, discriminator.trainable_variables))

EPOCHS = 10
BATCH_SIZE = 8

dataset = tf.data.Dataset.from_tensor_slices((low_imgs, high_imgs))
dataset = dataset.shuffle(1000).batch(BATCH_SIZE)

for epoch in range(EPOCHS):
    print(f"Epoch {epoch+1}/{EPOCHS}")

    for input_image, target in dataset:
        train_step(input_image, target)

from skimage.metrics import structural_similarity as ssim
import tensorflow as tf

def evaluate_model(gen, low, high):
    psnr_list = []
    ssim_list = []

    for i in range(50):
        inp = low[i:i+1]
        target = high[i]

        pred = gen(inp, training=False)[0].numpy()

        psnr = tf.image.psnr(pred, target, max_val=1.0)
        ssim_val = ssim(pred.squeeze(), target.squeeze(), data_range=1.0)

        psnr_list.append(psnr.numpy())
        ssim_list.append(ssim_val)

    print("Avg PSNR:", np.mean(psnr_list))
    print("Avg SSIM:", np.mean(ssim_list))

evaluate_model(generator, low_imgs, high_imgs)

import matplotlib.pyplot as plt

def show_results(idx):
    inp = low_imgs[idx]
    target = high_imgs[idx]
    pred = generator(inp[np.newaxis,...])[0]

    plt.figure(figsize=(12,4))

    plt.subplot(1,3,1)
    plt.title("Low Quality")
    plt.imshow(inp.squeeze(), cmap='gray')

    plt.subplot(1,3,2)
    plt.title("Generated")
    plt.imshow(pred.numpy().squeeze(), cmap='gray')

    plt.subplot(1,3,3)
    plt.title("High Quality")
    plt.imshow(target.squeeze(), cmap='gray')

    plt.show()

show_results(10)



